"""Exercise 5 — the app under test. Complete and working — do not edit this file.

The app has:
- NoteCreate with a @field_validator that rejects blank titles and strips whitespace
- NoteUpdate with extra="forbid" and a @model_validator requiring at least one field
- NoteService with create / get / patch
- _notify() that calls httpx.post when WEBHOOK_URL is set
- A module-level WEBHOOK_URL string (so monkeypatch can swap it in tests)
"""

from contextlib import asynccontextmanager
from typing import Annotated

import httpx
from fastapi import FastAPI, Depends, Request
from fastapi.responses import JSONResponse
from pydantic import ConfigDict, field_validator, model_validator
from sqlmodel import SQLModel, Field, Session, create_engine, select
from sqlmodel.pool import StaticPool

# --- DB setup ---

engine = create_engine(
    "sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool
)


def get_session():
    with Session(engine) as session:
        yield session


SessionDep = Annotated[Session, Depends(get_session)]


@asynccontextmanager
async def lifespan(app):
    SQLModel.metadata.create_all(engine)
    yield


app = FastAPI(lifespan=lifespan)
SQLModel.metadata.create_all(engine)

# Module-level URL — monkeypatch can replace this in tests
WEBHOOK_URL: str = ""


# --- Domain exception ---

class NoteNotFoundError(Exception):
    def __init__(self, note_id: int):
        self.note_id = note_id


@app.exception_handler(NoteNotFoundError)
async def note_not_found_handler(request: Request, exc: NoteNotFoundError):
    return JSONResponse(status_code=404, content={"error": f"Note {exc.note_id} does not exist"})


# --- Model ---

class Note(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    title: str
    done: bool = False


# --- Schemas ---

class NoteCreate(SQLModel):
    title: str
    done: bool = False

    @field_validator("title")
    @classmethod
    def title_must_not_be_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("title must not be blank")
        return v.strip()


class NoteUpdate(SQLModel):
    model_config = ConfigDict(extra="forbid")

    title: str | None = None
    done: bool | None = None

    @field_validator("title")
    @classmethod
    def title_must_not_be_blank(cls, v: str | None) -> str | None:
        if v is not None and not v.strip():
            raise ValueError("title must not be blank")
        return v.strip() if v else v

    @model_validator(mode="after")
    def at_least_one_field(self) -> "NoteUpdate":
        if self.title is None and self.done is None:
            raise ValueError("provide at least one field to update")
        return self


class NoteRead(SQLModel):
    id: int
    title: str
    done: bool


# --- Side effect ---

def _notify(note: Note) -> None:
    """Best-effort webhook — failures are swallowed."""
    if not WEBHOOK_URL:
        return
    try:
        httpx.post(WEBHOOK_URL, json={"id": note.id, "title": note.title}, timeout=5)
    except Exception:
        pass


# --- Service ---

class NoteService:
    def get(self, db: Session, note_id: int) -> Note:
        note = db.get(Note, note_id)
        if not note:
            raise NoteNotFoundError(note_id)
        return note

    def create(self, db: Session, payload: NoteCreate) -> Note:
        note = Note(title=payload.title, done=payload.done)
        db.add(note)
        db.commit()
        db.refresh(note)
        _notify(note)
        return note

    def patch(self, db: Session, note_id: int, payload: NoteUpdate) -> Note:
        note = self.get(db, note_id)
        for key, value in payload.model_dump(exclude_unset=True).items():
            setattr(note, key, value)
        db.add(note)
        db.commit()
        db.refresh(note)
        return note


note_service = NoteService()


# --- Router ---

@app.post("/notes", response_model=NoteRead, status_code=201)
async def create_note(payload: NoteCreate, session: SessionDep):
    return note_service.create(session, payload)


@app.get("/notes/{note_id}", response_model=NoteRead)
async def get_note(note_id: int, session: SessionDep):
    return note_service.get(session, note_id)


@app.patch("/notes/{note_id}", response_model=NoteRead)
async def patch_note(note_id: int, payload: NoteUpdate, session: SessionDep):
    return note_service.patch(session, note_id, payload)
