"""Add owner column to note.

This migration shows what create_all() *cannot* do: alter an existing table.
Once a table exists, create_all() is a no-op — you need a migration like this.

Generated by: alembic revision --autogenerate -m "add owner to note"
"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("note", sa.Column("owner", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column("note", "owner")
